//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertisementList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public advertisementList()
        {
            this.jobDetails = new HashSet<jobDetail>();
        }
    
        public long advertisementRefID { get; set; }
        public long empID { get; set; }
        public string advertisementimageURL { get; set; }
        public bool advertisementRefstatus { get; set; }
        public string advertisementURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobDetail> jobDetails { get; set; }
    }
}
