//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oriondbEntities1 : DbContext
    {
        public oriondbEntities1()
            : base("name=oriondbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_error_log> app_error_log { get; set; }
        public virtual DbSet<genderList> genderLists { get; set; }
        public virtual DbSet<qendidateGraduation> qendidateGraduations { get; set; }
        public virtual DbSet<qendidateList> qendidateLists { get; set; }
        public virtual DbSet<qendidatePGraduation> qendidatePGraduations { get; set; }
        public virtual DbSet<qendidatePHD> qendidatePHDs { get; set; }
        public virtual DbSet<qenEmpDetail> qenEmpDetails { get; set; }
        public virtual DbSet<qenHigherSecondary> qenHigherSecondaries { get; set; }
        public virtual DbSet<qenReference> qenReferences { get; set; }
        public virtual DbSet<qenSecondary> qenSecondaries { get; set; }
        public virtual DbSet<qenSkill> qenSkills { get; set; }
        public virtual DbSet<skill> skills { get; set; }
    }
}
