//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qendidateTestSchedule
    {
        public long mailSendID { get; set; }
        public long jobID { get; set; }
        public long qenID { get; set; }
        public bool mailSentTestScheduled { get; set; }
        public bool mailReceivedscheduled { get; set; }
        public Nullable<System.DateTime> testScheduledDateTime { get; set; }
        public System.DateTime dataIsCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public string ReasonReschedule { get; set; }
        public int testScheduleCountInt { get; set; }
        public Nullable<long> questionPaperID { get; set; }
        public Nullable<System.DateTime> questionPaperSentDateTime { get; set; }
        public Nullable<System.DateTime> examAttemptedDateTime { get; set; }
        public Nullable<System.DateTime> examSubmittedDateTime { get; set; }
        public int examMarks { get; set; }
        public bool isExamAttempted { get; set; }
        public bool isExamSubmitted { get; set; }
        public bool IsMeetScheduled { get; set; }
    
        public virtual jobDetail jobDetail { get; set; }
        public virtual qendidateList qendidateList { get; set; }
    }
}
