//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qenEmpDetail
    {
        public long qenEmploymentNum { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> qenEmpFrom { get; set; }
        public string jobDescription { get; set; }
        public Nullable<System.DateTime> qenEmpTo { get; set; }
        public Nullable<double> qenSalary { get; set; }
        public string qenPosition { get; set; }
        public Nullable<System.DateTime> dataIsCreated { get; set; }
        public Nullable<System.DateTime> dataIsUpdated { get; set; }
        public long qenID { get; set; }
        public string qenRoleInProject { get; set; }
        public Nullable<int> teamSize { get; set; }
        public string jobLocation { get; set; }
        public Nullable<bool> isPresent { get; set; }
        public string projectDescription { get; set; }
    
        public virtual qendidateList qendidateList { get; set; }
    }
}
