//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qenResume
    {
        public long qenID { get; set; }
        public int qenResumeID { get; set; }
        public string qenResumeName { get; set; }
        public string qenResume1 { get; set; }
    
        public virtual qendidateList qendidateList { get; set; }
    }
}
