//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qenSecondary
    {
        public long qenSecondary1 { get; set; }
        public long qenID { get; set; }
        public string schoolName { get; set; }
        public Nullable<int> secondaryPassYear { get; set; }
        public Nullable<double> secondaryPercentage { get; set; }
        public string secondaryBoard { get; set; }
        public Nullable<System.DateTime> dataIsCreated { get; set; }
        public Nullable<System.DateTime> dataIsUpdated { get; set; }
        public string secondarySubjects { get; set; }
    
        public virtual qendidateList qendidateList { get; set; }
    }
}
