//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int stateID { get; set; }
        public string stateName { get; set; }
        public int CountryID { get; set; }
    
        public virtual country country { get; set; }
    }
}
